// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmxaWwKuqrQvvCNCqeyH1XjUyJ5o-RByk',
    appId: '1:133140867893:web:efbf1833b6fa162d1a3a7c',
    messagingSenderId: '133140867893',
    projectId: 'hygia-9f3bd',
    authDomain: 'hygia-9f3bd.firebaseapp.com',
    storageBucket: 'hygia-9f3bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2o605hih93uxgrEjBDMSmUAoQJa7VBKI',
    appId: '1:133140867893:android:fc88e7873e9607b31a3a7c',
    messagingSenderId: '133140867893',
    projectId: 'hygia-9f3bd',
    storageBucket: 'hygia-9f3bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpblI_TV5m8pLFP-bZPHjiTHdh31_BbkQ',
    appId: '1:133140867893:ios:270694546cea590b1a3a7c',
    messagingSenderId: '133140867893',
    projectId: 'hygia-9f3bd',
    storageBucket: 'hygia-9f3bd.firebasestorage.app',
    iosBundleId: 'com.example.hygieneV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpblI_TV5m8pLFP-bZPHjiTHdh31_BbkQ',
    appId: '1:133140867893:ios:270694546cea590b1a3a7c',
    messagingSenderId: '133140867893',
    projectId: 'hygia-9f3bd',
    storageBucket: 'hygia-9f3bd.firebasestorage.app',
    iosBundleId: 'com.example.hygieneV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmxaWwKuqrQvvCNCqeyH1XjUyJ5o-RByk',
    appId: '1:133140867893:web:852bc3038d8e16841a3a7c',
    messagingSenderId: '133140867893',
    projectId: 'hygia-9f3bd',
    authDomain: 'hygia-9f3bd.firebaseapp.com',
    storageBucket: 'hygia-9f3bd.firebasestorage.app',
  );
}
