import 'package:flutter/material.dart';
import 'task_definition.dart';

const builtInTasks = <TaskDefinition>[
  TaskDefinition(
    id: 'handwash',
    name: 'Wash hands',
    shortDescription: 'Wash hands with soap and safe water during work.',
    icon: Icons.wash_rounded,
    category: TaskCategory.personalHygiene,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 1,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 5,
        valuePoints: 8,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 10,
        valuePoints: 10,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 15,
        valuePoints: 12,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 20,
        valuePoints: 14,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 25,
        valuePoints: 16,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'wear_protective_clothing',
    name: 'Wear protective clothing',
    shortDescription: 'Wear clean clothes, an apron, and a head covering.',
    icon: Icons.checkroom_rounded,
    category: TaskCategory.personalHygiene,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 30,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 35,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 40,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 45,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 50,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'health_check',
    name: 'Health check',
    shortDescription: 'Confirm that you are fit to handle food today.',
    icon: Icons.health_and_safety_rounded,
    category: TaskCategory.personalHygiene,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: false,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 10,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 12,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 15,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 18,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 20,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'separate_raw_and_cooked',
    name: 'Separate raw and cooked food',
    shortDescription:
        'Use separate tools and containers to avoid contamination.',
    icon: Icons.swap_horiz_rounded,
    category: TaskCategory.foodHandling,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 16,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 18,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 20,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 22,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 30,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'handle_rte_safely',
    name: 'Handle ready-to-eat food safely',
    shortDescription: 'Use tongs, spoons, or gloves instead of bare hands.',
    icon: Icons.restaurant_rounded,
    category: TaskCategory.foodHandling,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 5,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 5,
        valuePoints: 8,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 8,
        valuePoints: 10,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 12,
        valuePoints: 12,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 16,
        valuePoints: 14,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 20,
        valuePoints: 16,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'cook_food_thoroughly',
    name: 'Cook food thoroughly',
    shortDescription: 'Cook food properly before serving customers.',
    icon: Icons.local_fire_department_rounded,
    category: TaskCategory.foodHandling,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 30,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 1,
        valuePoints: 20,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 2,
        valuePoints: 18,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 2,
        valuePoints: 22,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 3,
        valuePoints: 20,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 3,
        valuePoints: 24,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'wash_raw_produce',
    name: 'Wash raw produce safely',
    shortDescription: 'Wash fruits and vegetables using safe water.',
    icon: Icons.eco_rounded,
    category: TaskCategory.foodHandling,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: false,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 12,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 14,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 15,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 15,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 16,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'use_safe_water',
    name: 'Use safe water',
    shortDescription: 'Use potable water for cooking, washing, and serving.',
    icon: Icons.water_drop_rounded,
    category: TaskCategory.waterSafety,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 25,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 28,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 32,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 36,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 40,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'store_water_safely',
    name: 'Store water safely',
    shortDescription: 'Keep water in clean, closed containers with a tap.',
    icon: Icons.storage_rounded,
    category: TaskCategory.waterSafety,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 14,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 16,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 18,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 20,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 24,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'safe_ice_handling',
    name: 'Handle ice safely',
    shortDescription:
        'Use clean ice from safe water and store it hygienically.',
    icon: Icons.ac_unit_rounded,
    category: TaskCategory.waterSafety,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: false,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 12,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 14,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 15,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 16,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 18,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'clean_utensils',
    name: 'Clean utensils',
    shortDescription: 'Wash and sanitize utensils after use.',
    icon: Icons.local_drink_rounded,
    category: TaskCategory.equipmentCare,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 15,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 4,
        valuePoints: 8,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 6,
        valuePoints: 10,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 8,
        valuePoints: 12,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 10,
        valuePoints: 14,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 12,
        valuePoints: 16,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'clean_surfaces',
    name: 'Clean surfaces',
    shortDescription: 'Keep the workspace and preparation areas clean.',
    icon: Icons.cleaning_services_rounded,
    category: TaskCategory.equipmentCare,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 20,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 4,
        valuePoints: 8,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 6,
        valuePoints: 10,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 8,
        valuePoints: 12,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 10,
        valuePoints: 14,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 12,
        valuePoints: 16,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'store_utensils_properly',
    name: 'Store utensils properly',
    shortDescription: 'Keep clean utensils upside-down on raised racks.',
    icon: Icons.inventory_rounded,
    category: TaskCategory.equipmentCare,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: false,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 20,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 24,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 28,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 32,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 36,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'change_wiping_cloth',
    name: 'Change wiping cloth',
    shortDescription: 'Wash or replace wiping cloth regularly during the day.',
    icon: Icons.clean_hands_rounded,
    category: TaskCategory.equipmentCare,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 240,
    requiresShopOpen: true,
    isCritical: false,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 2,
        valuePoints: 10,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 3,
        valuePoints: 12,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 4,
        valuePoints: 14,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 5,
        valuePoints: 16,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 6,
        valuePoints: 18,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'cover_food',
    name: 'Cover food',
    shortDescription: 'Keep food covered to protect it from dust and flies.',
    icon: Icons.inventory_2_rounded,
    category: TaskCategory.storage,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 15,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 8,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 10,
        streakDaysRequired: 3,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 12,
        streakDaysRequired: 7,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 14,
        streakDaysRequired: 14,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 12,
        valuePoints: 16,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'temperature_control',
    name: 'Check food temperature',
    shortDescription: 'Keep hot food hot and cold food cold during service.',
    icon: Icons.thermostat_rounded,
    category: TaskCategory.storage,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 18,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 20,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 22,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 24,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 25,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'check_stock_fifo',
    name: 'Check stock and FIFO',
    shortDescription: 'Check expiry dates and use older stock first.',
    icon: Icons.event_note_rounded,
    category: TaskCategory.storage,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 25,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 30,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 35,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 40,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 45,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'leftover_handling',
    name: 'Handle leftovers safely',
    shortDescription:
        'Discard unsafe leftovers or store them safely for later.',
    icon: Icons.kitchen_rounded,
    category: TaskCategory.storage,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: false,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 25,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 28,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 32,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 36,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 40,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'keep_stall_clean',
    name: 'Keep stall clean',
    shortDescription: 'Maintain a clean vending area away from dirt and pests.',
    icon: Icons.storefront_rounded,
    category: TaskCategory.environment,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 30,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 35,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 40,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 45,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 50,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'use_raised_surfaces',
    name: 'Use raised surfaces',
    shortDescription: 'Keep food and utensils off the ground.',
    icon: Icons.table_restaurant_rounded,
    category: TaskCategory.environment,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 20,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 24,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 28,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 32,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 36,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'pest_control',
    name: 'Manage pests',
    shortDescription: 'Keep flies, rodents, and animals away from the stall.',
    icon: Icons.pest_control_rounded,
    category: TaskCategory.environment,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 16,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 18,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 20,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 20,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 24,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'manage_waste',
    name: 'Manage waste',
    shortDescription: 'Keep rubbish covered, separated, and removed daily.',
    icon: Icons.delete_outline_rounded,
    category: TaskCategory.waste,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: false,
    isCritical: true,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 30,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 35,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 40,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 45,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 50,
        streakDaysRequired: 30,
      ),
    ],
  ),

  TaskDefinition(
    id: 'separate_waste',
    name: 'Separate waste',
    shortDescription: 'Separate liquid waste, food remains, and solid waste.',
    icon: Icons.recycling_rounded,
    category: TaskCategory.waste,
    kind: TaskKind.repeatable,
    mediaAsset: null,
    minGapMinutes: 60,
    requiresShopOpen: true,
    isCritical: false,
    levels: [
      TaskLevel(
        level: 1,
        timesPerDayTarget: 3,
        valuePoints: 20,
        streakDaysRequired: 0,
      ),
      TaskLevel(
        level: 2,
        timesPerDayTarget: 5,
        valuePoints: 24,
        streakDaysRequired: 5,
      ),
      TaskLevel(
        level: 3,
        timesPerDayTarget: 7,
        valuePoints: 28,
        streakDaysRequired: 10,
      ),
      TaskLevel(
        level: 4,
        timesPerDayTarget: 9,
        valuePoints: 32,
        streakDaysRequired: 20,
      ),
      TaskLevel(
        level: 5,
        timesPerDayTarget: 10,
        valuePoints: 36,
        streakDaysRequired: 30,
      ),
    ],
  ),
];
